### ISSUE TITLE
URL Misdirection

### ISSUE THREAD

**Issue by Elisiah** [gihanmarasingha/miu-game-pages#1]
README.md | Line 3

Current URL link:  `[online](https://gihanmarasingha.github.io/miu-game-page/html/).` -> [online](https://gihanmarasingha.github.io/miu-game-page/html/).
Corrected URL link:     `[online](https://gihanmarasingha.github.io/miu-game-pages/html/).` -> [online](https://gihanmarasingha.github.io/miu-game-pages/html/).

This will allow people to find the game, at first I thought the site may just be faulty until I saw the URL mismatch from the repo name

**Comment by gihanmarasingha** [comment]
Thanks!
